// Specific TypeScript code to manage options for OpenAI GPT

// Adds an event listener to the selection of the voice value for the Text 2
// Speech audio generated by OpenAI, ensuring the correct display of the audio
// preview file.
document.querySelector('#openaiText2SpeechVoice').addEventListener('change', (event) => {
    const currentAudio = (document.querySelector('#openaiText2SpeechVoicePreview audio') as HTMLAudioElement)

    currentAudio.pause()
    currentAudio.currentTime = 0

    currentAudio.setAttribute('src', `https://cdn.openai.com/API/docs/audio/${(event.currentTarget as HTMLInputElement).value}.wav`)
})

// Adds an event to update the real-time selection of speed in the case of
// audio Text 2 Speech generated by OpenAI.
document.querySelector('#openaiText2SpeechSpeed').addEventListener('input', (event) => {
    const destination = (document.querySelector('label[for=openaiText2SpeechSpeed] span') as HTMLInputElement)
    const currentSpeedValue = (event.currentTarget as HTMLInputElement).value
    destination.innerText = parseFloat(currentSpeedValue).toFixed(2)
})
